"""Initial migration with sets, reps, intensity

Revision ID: 5b6719d70a8d
Revises: 
Create Date: 2025-07-25 18:05:12.971656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6719d70a8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intensity', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.drop_column('intensity')
        batch_op.drop_column('reps')
        batch_op.drop_column('sets')

    # ### end Alembic commands ###
