"""Add WorkoutPlan and WorkoutVideo tables

Revision ID: 6c0d36b32fc5
Revises: 0a81acce3cf5
Create Date: 2025-07-31 16:47:09.819374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c0d36b32fc5'
down_revision = '0a81acce3cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_video')
    op.drop_table('workout_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('bmi_category', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_video',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_plan_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('url', sa.VARCHAR(length=300), nullable=False),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
