"""Add admin plan fields to Workout

Revision ID: abd01f662949
Revises: 0f48ebda646c
Create Date: 2025-07-30 20:22:24.144187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd01f662949'
down_revision = '0f48ebda646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bmi_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('exercise_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('plan_details', sa.Text(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('plan_details')
        batch_op.drop_column('exercise_type')
        batch_op.drop_column('bmi_category')

    # ### end Alembic commands ###
