"""Initial create Dietplan and Meal tables

Revision ID: b952d67b9295
Revises: 3d6c962bd8de
Create Date: 2025-07-31 18:36:51.144760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b952d67b9295'
down_revision = '3d6c962bd8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('diet_plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('meal_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('diet_plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
